namespace BattleCity.Shared.Network;

/// <summary>Legacy client → server packet IDs (legacy/client/NetMessages.h).</summary>
public enum ClientMessageId : byte
{
    Tcp = 0,
    Version = 1,
    Login = 2,
    NewAccount = 3,
    ChatMessage = 4,
    SetState = 5,
    JobApp = 6,
    JobCancel = 7,
    HireAccept = 8,
    HireDecline = 9,
    Build = 10,
    Comms = 11,
    Fired = 12,
    ItemUp = 13,
    ItemDrop = 14,
    Death = 15,
    Demolish = 16,
    MedKit = 17,
    Cloak = 46,
    HitObject = 18,
    TcpPing = 19,
    Crash = 20,
    NextStep = 21,
    Successor = 22,
    Global = 23,
    Admin = 24,
    Ban = 25,
    IsHiring = 26,
    Walkie = 27,
    Update = 28,
    Shoot = 29,
    RefreshList = 38,
    Whisper = 44,
}
