namespace BattleCity.Shared.Network;

/// <summary>Legacy server → client packet IDs (legacy/server/NetMessages.h).</summary>
public enum ServerMessageId : byte
{
    Tcp = 0,
    LoginCorrect = 1,
    AppendNews = 2,
    ChatEcho = 3,
    ChatMessage = 4,
    PlayerData = 5,
    ChatCommand = 6,
    AddRemCity = 7,
    StateGame = 8,
    MayorHire = 9,
    MayorInInterview = 10,
    InterviewCancel = 11,
    MayorDeclined = 12,
    MayorUpdate = 13,
    CanBuild = 14,
    NewBuilding = 15,
    PlaceBuilding = 16,
    Error = 17,
    JoinData = 18,
    Comms = 19,
    Fired = 20,
    Finance = 21,
    ItemCount = 22,
    AddItem = 23,
    RemItem = 24,
    UpdatePop = 25,
    Death = 26,
    Orbed = 27,
    DestroyCity = 28,
    Demolish = 29,
    Hp = 30,
    RemBuilding = 31,
    Interview = 32,
    PickedUp = 33,
    Dropped = 34,
    TcpPong = 35,
    PointsUpdate = 36,
    MedKit = 37,
    Explosion = 38,
    Warp = 39,
    NextStep = 40,
    ItemLife = 41,
    Global = 42,
    Promotion = 43,
    Admin = 44,
    Kicked = 45,
    Update = 46,
    Shoot = 47,
    TurretLook = 48,
    TurretShoot = 49,
    SectorSent = 50,
    EditAccount = 51,
    InfoButton = 52,
    ClearPlayer = 53,
    MayorChanged = 54,
    RightClickCity = 55,
    Respawn = 56,
    Ban = 57,
    /// <summary>Legacy <c>smUnderAttack</c> (team alert when a city building is removed).</summary>
    UnderAttack = 58,
    AdminEdit = 59,
    ClickPlayer = 60,
    Whisper = 61,
    Count = 62,
    Cloak = 63,
}
