namespace BattleCity.Shared.Catalogs;

/// <summary>Playable city names indexed by city id (legacy/client/Structs.cpp CityList).</summary>
public static class CityCatalog
{
    public static IReadOnlyList<string> Names { get; } =
    [
        "Balkh",
        "Iqaluit",
        "Reykjavik",
        "Jumarity",
        "Helsinki",
        "Copenhagen",
        "Kiev",
        "Barentsburg",
        "Nunivak",
        "Algiers",
        "Paga Pago",
        "St. Johns",
        "Parana",
        "San Salvador de Jujuy",
        "Tallinn",
        "Bergen",
        "Bangui",
        "Annaba",
        "Andorra-la-Vella",
        "Bahia Blanca",
        "Posadas",
        "Santa Fe",
        "Buckland",
        "Kabul",
        "Lahij",
        "Banta",
        "Benguela",
        "Buenos Aires",
        "Resistencia",
        "Santiago del Estero",
        "Armidale",
        "Harbin",
        "Fajardo",
        "Blida",
        "Huambo",
        "Cordoba",
        "Rio Cuarto",
        "Kumayari",
        "Kuala Lumpur",
        "Mango",
        "Arequipa",
        "Constantine",
        "Luanda",
        "Corrientes",
        "Rosario",
        "Kirovakan",
        "Jakarta",
        "Skopje",
        "Bogota",
        "Canberra",
        "Pretoria",
        "Maracay",
        "Cambridge",
        "Laketown",
        "Hanoi",
        "Bishkek",
        "Tirana",
        "Dakar",
        "Aquin",
        "Bismarck",
        "Albany",
        "Manukau",
        "Utrecht",
        "Admin Inn",
    ];

    public static bool IsValidCityId(int cityId) => cityId >= 0 && cityId < Names.Count;

    public static string GetName(int cityId) => Names[cityId];
}
